### ISSUE TITLE
Arcyd: 'restart' can be interrupted, leaving arcyd offline

### ISSUE THREAD

**Issue by aevri** [bloomberg/phabricator-tools#42]
In the case where a user becomes impatient and uses Ctrl-C to abort, Arcyd will most likely stop and not be restarted.

Potentially we could not use the `var/command/killfile` scheme in this case and perhaps use a `var/command/reloadfile` scheme, so that the running daemon can have the responsibility of both stopping and starting.

**Comment by cs-shadow** [comment]
Is this fixed now as #50 has been merged?

**Comment by aevri** [comment]
Yup! We now have 'arcyd restart' for this. Thanks!
